### ISSUE TITLE
Quotes following numbers (Important!)

### ISSUE THREAD

**Issue by mkayeterry** [anguswg-ucsb/ingredient-slicer#1]
#### Examples:

- **Input to Function:** `'waffle round (4" dia)'`
- **Extracted Quantity:** `4`
- **Extracted Unit:** `None`
- **Problem:** If there are quotes following a number, the number is not considered as the quantity.
<br>

- **Input to Function:** `'fruit (4-2/3” long x 2-3/4” dia)'`
- **Extracted Quantity:** `4.67`
- **Extracted Unit:** `None`
- **Problem:** Same as above.

#### Note:
- This is the most significant/pressing issue I've found, and should be addressed ASAP.

**Comment by anguswg-ucsb** [comment]
Closing this issue. This issue has been addressed and numbers followed by `"` or any dimension-like unit (i.e. `inches`, `inch`, etc) will NOT be mistaken for quantities and instead will be parsed into the `dimensions` attribute of the parsed ingredient dictionary

**Comment by anguswg-ucsb** [comment]
Closing this issue. This issue has been addressed and numbers followed by `"` or any dimension-like unit (i.e. `inches`, `inch`, etc) will NOT be mistaken for quantities and instead will be parsed into the `dimensions` attribute of the parsed ingredient dictionary

**Comment by anguswg-ucsb** [comment]
Closing this issue. This issue has been addressed and numbers followed by `"` or any dimension-like unit (i.e. `inches`, `inch`, etc) will NOT be mistaken for quantities and instead will be parsed into the `dimensions` attribute of the parsed ingredient dictionary
