### ISSUE TITLE
Unrecognized units such as 'serving'

### ISSUE THREAD

**Issue by mkayeterry** [anguswg-ucsb/ingredient-slicer#2]
#### Examples:

- **Input to Function:** `'crackers (1 NLEA serving)'`
- **Extracted Quantity:** `1`
- **Extracted Unit:** `None`
- **Problem:** Serving not recognized as a unit.

- **Input to Function:** `'serving varied from 2-3 tacos per serving'`
- **Extracted Quantity:** `2.5`
- **Extracted Unit:** `None`
- **Problem:** Serving (1) or taco (2-3) not recognized.

#### Additional suggestions for units:
- bagel
- waffle
- tortilla
- twist
- pretzel
- bar
- cracker
- goldfish
- pancake
- fries
- taco
- steak
- frankfurter
- sapodilla
- melon
- wedge
- spear
- roast
- chop
- rack
- shank
- biscuit
- eclair
- sandwich
- pastry
- muffin
- gumdrop
- gummy (e.g., gummy worm, gummy bear, gummy fish)
- croissant
- hush puppy
- cone
- wafer
- cookie
- sausage
- cupcake
- pita
- cutlet
- envelope
- packet
- link

#### Note:
- Recognizing 'serving' and other specific unit terms would enhance parsing accuracy.

**Comment by anguswg-ucsb** [comment]
I don't see a great way of handling some of the units within the scope of this package (i.e. `bagels`, `tortillas`, are foods, and `wafer` could be a food or a unit). If you can think of a way of dealing with this, let me know!

Closing this issue for now.
