### ISSUE TITLE
Numbers associated with incorrect units

### ISSUE THREAD

**Issue by mkayeterry** [anguswg-ucsb/ingredient-slicer#3]
#### Examples:

- **Input to Function:** `'chop, excluding refuse (yield from 1 raw chop, with refuse, weighing 85 g)'`
- **Extracted Quantity:** `1`
- **Extracted Unit:** `'gram'`
- **Problem:** The numbers should remain associated with the units they appear by.
<br>

- **Input to Function:** `'oz shelled (32 nuts)'`
- **Extracted Quantity:** `32`
- **Extracted Unit:** `'ounce'`
- **Problem:** Same as above.

#### Note:
- Ensure that numbers are correctly associated with their respective primary and secondary units.

**Comment by anguswg-ucsb** [comment]
This was resolved in a prior release
